default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: home1234
  variables:
    sql_mode: TRADITIONAL

development:
  <<: *default
  database: pr21802-music-listening_development

test:
  <<: *default
  database: pr21802-music-listening_test

production:
  <<: *default
  database: pr21802-music-listening_production
  username: pr21802-music-listening
  password: <%= ENV['PR21802-MUSIC-LISTENING_DATABASE_PASSWORD'] %>
